# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Feature Branch

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: lolnotes_db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: lolnotesadmin
          MYSQL_PASSWORD: admin
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
